### PR TITLE
Chirp Tutorial: How to use Google's Chirp speech-to-text AI model on Google Cloud console.

### PR DESCRIPTION
**Pull request by abdibrokhim**
/claim #112 

Chirp Tutorial: How to use Google's Chirp speech-to-text AI model on Google Cloud console.

In this tutorial, we will learn how to set up Google Cloud console and use Chirp speech-to-text AI model. Sit back, relax and enjoy the tutorial!

### CODE REVIEW

**Comment by ezzcodeezzlife** [comment]
Please fix the file structure, no subdirectories

**Comment by abdibrokhim** [comment]
> Please fix the file structure, no subdirectories

what did you mean by subdirectories? audio and images folder?

**Comment by ezzcodeezzlife** [comment]
exactly, please jsut add the one file, put the audio stuff into a seperate new folder for now. thanks 🚀

**Comment by abdibrokhim** [comment]
> 

yeah, but audio itself in separate folder

**Comment by abdibrokhim** [comment]
@ezzcodeezzlife did you got what i mean?

If you see the image above there is one folder for tutorials itself and two subfolders for audio and images respectively, no other extra folders


chirp-tutorial ---
                        |-- audio ---
                                         |-- audio.mp3
                        |-- images ---
                                         |-- image.png
                        |-- tutorial.mdx

**Pull request closed without merging**
