### PR TITLE
Cohere Rerank Model: The Solution for Search AI Application

### PR DESCRIPTION
**Pull request by abdibrokhim**
Cohere Rerank Model: The Solution for Search AI Application

Beginner friendly tutorial on how to use Cohere Rerank Model for optimizing search algorithms and build Streamlit app with it.

### CODE REVIEW

**Comment by OlesiaZinchenko** [comment]
@ezzcodeezzlife could you take a look please?

**Comment by ezzcodeezzlife** [comment]
@abdibrokhim could you please add a screenshot where you run a working example in your streamlit application?

**Comment by abdibrokhim** [comment]
> @abdibrokhim could you please add a screenshot where you run a working example in your streamlit application?

sure

**Comment by ezzcodeezzlife** [comment]
@abdibrokhim thank you!

**Pull request closed without merging**
