### PR TITLE
ElevenLabs Tutorial: Build Your Fully Voiced AI-Powered Brainstorming Partner App

### PR DESCRIPTION
**Pull request by septiannugraha**
/claim #210 

Thank you for the opportunity! In this tutorial, we built a fully-voiced, brainstorming partner app, which is sure to engage and spark conversations and new ideas.

### CODE REVIEW

**Comment by VolodymyrStreltsov** [comment]
Hi. Thank you for your effort and time.

For now the tutorial cant be approved for publishing.

It needs to be improved.

Is this content AI generated? The probability of that is very high. AI generated content needs to be rewritted.

Also, based on your previous tutorials you tend to include very big part dedicated to introduce React or other not related to main topic technologies. Try to concentrate around main AI technology and only breathily include part for setup React and other not related stuffs.
Other request - not use completely the same texts and code snippets  in different tutorials:
Screenshot 2023-07-05 at 10 05 54 Screenshot 2023-07-05 at 10 06 01

**Comment by septiannugraha** [comment]
> Hi. Thank you for your effort and time.
> 
> For now the tutorial cant be approved for publishing.
> 
> It needs to be improved.
> 
> Is this content AI generated? The probability of that is very high. AI generated content needs to be rewritted.
> 
> Also, based on your previous tutorials you tend to include very big part dedicated to introduce React or other not related to main topic technologies. Try to concentrate around main AI technology and only breathily include part for setup React and other not related stuffs. Other request - not use completely the same texts and code snippets in different tutorials: Screenshot 2023-07-05 at 10 05 54 Screenshot 2023-07-05 at 10 06 01

Hi, thank you for the follow up. 

First of all, no, this content is not AI-generated. I do use AI to critique my writing for grammatical error, typos and/or missing details. But the writing style, the ideas, the contents are all mine.

Also you're right about the fact that I kind of heavily introduce technologies, sometimes more than the main topics themselves (AI tools). I'll try to improve my writing. Any clues on which parts are considered AI-generated?

Thank you!

**Comment by septiannugraha** [comment]
Here I've pushed my revision, which includes:
- complete rewrite of the introductions, project initialization and coding part.
- reducing the ReactJS explanations part to make room for explaining the details of the AI tools used (ElevenLabs and Anthropic's Claude)

Please review my changes. Thank you 🙏 @VolodymyrStreltsov @ezzcodeezzlife

**Comment by septiannugraha** [comment]
Hi @VolodymyrStreltsov, I would like to know how much is the threshold for deciding if a content is indeed AI-generated.

image

In the image above, I've tested my other tutorial with Copyleaks services. It detected my written lines as AI-generated, albeit only 70%-ish. This is strange because I even had parentheses and emoji which would make it sounds more personalized.

**Comment by septiannugraha** [comment]
Thank you for the SEO check @VolodymyrStreltsov, is my PR here ready to publish also? If it still isn't, please let me know!

**Comment by VolodymyrStreltsov** [comment]
Hi @septiannugraha Thanks that you rewrite some parts of this tutorial.  For now we have a couple tutorials in a row with big part of the same content. If you can, do not reintroduce readers every time into React and Flask and other not related technologies. We need a bit more time for analising this content. Thank you

**Comment by septiannugraha** [comment]
> Hi @septiannugraha Thanks that you rewrite some parts of this tutorial. For now we have a couple tutorials in a row with big part of the same content. If you can, do not reintroduce readers every time into React and Flask and other not related technologies. We need a bit more time for analising this content. Thank you

Thank you for the reply. This is my last React-based tutorial for now, as I'm considering another, much simpler technology such as Streamlit for building the user interface.

**Comment by ezzcodeezzlife** [comment]
ok, good to know

**Pull request merged**
