### PR TITLE
Imagen by Vertex AI Tutorial

### PR DESCRIPTION
**Pull request by abdibrokhim**
/claim #216

Detailed guide to use Imagen by Vertex AI. Generate images, edit and analyze them.

### CODE REVIEW

**Comment by ezzcodeezzlife** [comment]
`image

edit`

What are these for? 

Can you maybe get access and build a small application? Thanks! @abdibrokhim

**Comment by abdibrokhim** [comment]
> ```
> image
> edit
> ```
> 
> What are these for?
> 
> Can you maybe get access and build a small application? Thanks! @abdibrokhim

i dont have access thats why for now i leave as a blank.

**Comment by abdibrokhim** [comment]
i already asked Olesia but she is not replying me

**Comment by ezzcodeezzlife** [comment]
Please just upload you images to that service, I will upload them for you then

https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md

**Comment by abdibrokhim** [comment]
> Please just upload you images to that service, I will upload them for you then
> 
> https://github.com/lablab-ai/community-content/blob/main/tutorials/README.md

hello, ok

**Comment by abdibrokhim** [comment]
Hello, @ezzcodeezzlife done ✅. i updated tutorial and included as many images.

**Pull request merged**
