### PR TITLE
TruLens + Google Vertex AI Tutorial: Building RAG Applications

### PR DESCRIPTION
**Pull request by adamrayed**
/claim #398

### CODE REVIEW

**Comment by ezzcodeezzlife** [comment]
Also good stuff, but the same problem with the images: https://github.com/lablab-ai/community-content/pull/415 Please fix and then its ready to go 🚀

**Comment by adamrayed** [comment]
> Also good stuff, but the same problem with the images: #415 Please fix and then its ready to go 🚀 @adamrayed

Just used another hosting provider and the images are better now

**Comment by adamrayed** [comment]
Is it proper now @ezzcodeezzlife

**Comment by adamrayed** [comment]
> > Also good stuff, but the same problem with the images: #415 Please fix and then its ready to go 🚀 @adamrayed
> 
> Just used another hosting provider and the images are better now

?

**Pull request merged**
