### PR TITLE
Tutorial on how to summarize a long form arxiv articles and generate semantically related articles

### PR DESCRIPTION
**Pull request by Raghavan1988**
In this scholarly article, I have written a tutorial with following contributions
1. Building an embedding based annoy index for 2M arxiv articles 
2. Generating a summary for ARXIV article
3. Using annoy to retrieve semantically related articles 
4. Using Langchain + GPT 3.5 to generate summary and grounded idea generator based on related articles in the field.
Technologies used: annoy, langchain, sentence bert, GPT 3.5

### CODE REVIEW

**Comment by ezzcodeezzlife** [comment]
Thank you for the tutorial. This was not a bounty claim, right? @Raghavan1988

**Comment by Raghavan1988** [comment]
No. This is not a bounty claim

**Comment by Raghavan1988** [comment]
@ezzcodeezzlife Please let me know if any changes are required. I am happy to make the changes. I have also run the code end to end to test correctness.

**Comment by OlesiaZinchenko** [comment]
@ezzcodeezzlife The SEO content check ready

@Raghavan1988 Please, feel free to add links to your website / social media in the end if the article, so people can connect with you.

**Comment by Raghavan1988** [comment]
@OlesiaZinchenko 
For some reason, github is not allowing me to edit the PR directly. 
https://www.linkedin.com/in/raghavanmit/ is my linkedin profile. 

I am ok with not having the social media link. I will add in my future articles.

**Comment by ezzcodeezzlife** [comment]
@Raghavan1988 thank you very much for this cool tutorial! 🚀 Going online right now 💯

**Pull request merged**
