### PR TITLE
AudioCraft: How to create music with Meta AI

### PR DESCRIPTION
**Pull request by alhuissi**
Audiocraft tutorial: How to create music with Audiocraft

How to install Audiocraft, MetaAI open source audio generation tool, and create music over 2 minutes long.

/claim #254

### CODE REVIEW

**Comment by ezzcodeezzlife** [comment]
@alhuissi Hey, i think running the webui is very cool, but its not super usefull for hackathon participants who want to integrate this into their own codebase. Can you add more paragrpah about how to use this within some code?

thank you! 🚀

**Comment by alhuissi** [comment]
@ezzcodeezzlife Just added a section about how to import and use audiocraft in a streamlit app, that generates audio from a URL's summarized content (with ChatGPT's help). Hope it's useful enough, I actually had a lot of fun doing this one :).

Cheers

**Comment by ezzcodeezzlife** [comment]
@alhuissi very cool thanks!

**Comment by ezzcodeezzlife** [comment]
@VolodymyrStreltsov also check SEO here please 😊

**Review by VolodymyrStreltsov — APPROVED** [review]

**Pull request merged**
