### PR TITLE
Cohere blog article for Hackernoon

### PR DESCRIPTION
**Pull request by shreya50**
Please review document regarding Issue #226

### CODE REVIEW

**Comment by septiannugraha** [comment]
> Please review document regarding Issue #226

Don't forget to claim the issue! use `/claim #number` command.

**Comment by ezzcodeezzlife** [comment]
And please follow the format in the instructions, not a docx file. Thank you 🚀

**Comment by shreya50** [comment]
> 

Hi, the issue seems to be for hackernoon, not lablab.ai. I've read the hackernoon guidelines and they don't require .mdx for so I'm confused if I'm supposed to publish the article myself or just send the document file

**Comment by septiannugraha** [comment]
> > 
> 
> Hi, the issue seems to be for hackernoon, not lablab.ai. I've read the hackernoon guidelines and they don't require .mdx for so I'm confused if I'm supposed to publish the article myself or just send the document file

Don't worry, lablab.ai will do the article submission to Hackernoon on your behalf. I made a pull request for a Hackernoon article (#219) too, and I use .mdx.

**Comment by duccikk** [comment]
> Hi, the issue seems to be for hackernoon, not lablab.ai. I've read the hackernoon guidelines and they don't require .mdx for so I'm confused if I'm supposed to publish the article myself or just send the document file

hey hey, you have to send the file to us, we are publishing by ourselves at lablab.ai Hakernoon account

**Comment by shreya50** [comment]
> > > 
> > 
> > 
> > Hi, the issue seems to be for hackernoon, not lablab.ai. I've read the hackernoon guidelines and they don't require .mdx for so I'm confused if I'm supposed to publish the article myself or just send the document file
> 
> Don't worry, lablab.ai will do the article submission to Hackernoon on your behalf. I made a pull request for a Hackernoon article (#219) too, and I use .mdx.

Thanks for the information!

**Comment by septiannugraha** [comment]
> > > > 
> > > 
> > > 
> > > Hi, the issue seems to be for hackernoon, not lablab.ai. I've read the hackernoon guidelines and they don't require .mdx for so I'm confused if I'm supposed to publish the article myself or just send the document file
> > 
> > 
> > Don't worry, lablab.ai will do the article submission to Hackernoon on your behalf. I made a pull request for a Hackernoon article (#219) too, and I use .mdx.
> 
> Thanks for the information!

No problem, just trying to help a fellow content writer 😁

**Comment by shreya50** [comment]
Hi, I've converted the article to .mdx. Please excuse me for the commits, I'm not Github savvy.

**Comment by septiannugraha** [comment]
> Hi, I've converted the article to .mdx. Please excuse me for the commits, I'm not Github savvy.

Good work! don't forget to claim the bounty by referencing the ID of the issue (#226)

**Comment by ezzcodeezzlife** [comment]
@duccikk please have a look at the content and say if its ready for publishing 🚀

**Comment by duccikk** [comment]
> @duccikk please have a look at the content and say if its ready for publishing 🚀

hey hey! Yes, it is ready! Hackernoon are checking it :)

**Review by shreya50 — COMMENTED** [review]
/claim #226

**Pull request merged**
