### PR TITLE
Cohere Rerank Model: The Solution For Search AI Application

### PR DESCRIPTION
**Pull request by Sanchay-T**
#363

### CODE REVIEW

**Comment by OlesiaZinchenko** [comment]
Hi @ezzcodeezzlife Could you please make sure review and publish it in the next 2 days?

**Comment by OlesiaZinchenko** [comment]
@ezzcodeezzlife it looks great on my side

**Review by ezzcodeezzlife — CHANGES_REQUESTED** [review]
@Sanchay-T thank you for your contribution but I have to request some urgent changes:

- [ ] Make sure you only host images on https://iili.io (i was some freeimage links in there).
- [ ] Only use markdown: No html elements other than the  React compoent. Eveything around this is explained in the readme.mde for the tutorials

In terms of content its a very nice tutorial and we would love to publish it 🤍

**Comment by Sanchay-T** [comment]
Okay i'll do the same

**Comment by Sanchay-T** [comment]
@ezzcodeezzlife  is this proper?

**Review by Sanchay-T — COMMENTED** [review]
Done

**Comment by OlesiaZinchenko** [comment]
@ezzcodeezzlife Hi! Are we good to go live with this tutorial?

**Review by ezzcodeezzlife — CHANGES_REQUESTED** [review]
Same here with the images: Please check the readme on how to add images. @Sanchay-T

**Comment by ezzcodeezzlife** [comment]
@Sanchay-T

**Comment by Sanchay-T** [comment]
@ezzcodeezzlife

**Comment by ezzcodeezzlife** [comment]
@OlesiaZinchenko this conent was merged in https://github.com/lablab-ai/community-content/commit/2489358ffcde374cea590abc1be6d6b48cb1e28f

**Pull request closed without merging**
