### PR TITLE
SuperAGI tutorial: Generate a codebase and push it to GitHub

### PR DESCRIPTION
**Pull request by DonGuillotine**
SuperAGI tutorial: Generate a codebase and push it to GitHub.

An Intermediate-level tutorial on generating a codebase and push it to GitHub with SuperAGI

/claim #251

### CODE REVIEW

**Comment by ezzcodeezzlife** [comment]
@DonGuillotine please update your image link to this format: 

`MusicGen Dashboard`

In the readme its explained how and where to do this. Thank you ❤️

**Comment by DonGuillotine** [comment]
> @DonGuillotine please update your image link to this format:
> 
> `MusicGen Dashboard`
> 
> In the readme its explained how and where to do this. Thank you ❤️

Hi @ezzcodeezzlife, apologies for the confusion. Will update the image links now.

**Comment by DonGuillotine** [comment]
@ezzcodeezzlife I have updated the image links, can you confirm?

**Comment by DonGuillotine** [comment]
> @DonGuillotine appreciate it. could you please also add some more content (this is suppost to be a intermediate tutorial)? Maybe go a bit more into detail. Some ideas here could be:
> 
> * what happends in the background?
> * showcase a generated project.
> * Whats a good way to prompt it to get good results?
> 
> and more..
> 
> Thanks you ❤️

Hello @ezzcodeezzlife, thanks for pointing this out. I will update this accordingly.

**Comment by DonGuillotine** [comment]
Hi @ezzcodeezzlife, I have added more detail to the tutorial. I also added an indepth "behind the scenes" section that explains how everything works.

Hope it's in an intermediate level. If there are more things to fixup or update, kindly let me know.

**Pull request merged**
