### PR TITLE
Hackathon Tutorial: How to Protect API Key in Your Hackathon Demo

### PR DESCRIPTION
**Pull request by abdibrokhim**
Hackathon Tutorial: How to Protect API Key in Your Hackathon Demo

A beginner-level tutorial on protecting API key in the demo product in the hackathons.

/claim #256

### CODE REVIEW

**Comment by OlesiaZinchenko** [comment]
@abdibrokhim Please, take a deeper look on the risks of not protecting the API Key - using H3 headings for each. 
In addition, please, make sure to expand the intro text, onboarding readers in the Hackathon process, and mentioning the problem statement (they have to create a product demo, and why should they case about the security on that early stage)

**Comment by ezzcodeezzlife** [comment]
really nice, could you please add one small tect about that most hosting plattforms like vercel or streamlit cloud offer ways to add the env api keys in a private way so they are not visible by the public but still used in the project

thanks! then its ready to go online 🤟🏼

**Comment by abdibrokhim** [comment]
> really nice, could you please add one small tect about that most hosting plattforms like vercel or streamlit cloud offer ways to add the env api keys in a private way so they are not visible by the public but still used in the project
> 
> thanks! then its ready to go online 🤟🏼

Hello, actually it is there. I showcased with streamlit

**Comment by ezzcodeezzlife** [comment]
Ah yes ok then lets goo 🚀

**Comment by ezzcodeezzlife** [comment]
@VolodymyrStreltsov please also hceck SEO here? thank you

**Pull request merged**
