### PR TITLE
[DUPLICATE] StableCode Tutorial: How to get started with StableCode

### PR DESCRIPTION
**Pull request by abdibrokhim**
StableCode Tutorial: How to get started with StableCode

Brief explanations of key concepts and step-by-step guide to get started with StableCode

/claim 255

### CODE REVIEW

**Comment by ezzcodeezzlife** [comment]
@abdibrokhim very nice, love this one! 🚀 

one small thing: could you add a paragraph on how to use these models with the hugging face inference api? 

- https://huggingface.co/docs/api-inference/index
- https://huggingface.co/stabilityai/stablecode-instruct-alpha-3b & https://huggingface.co/stabilityai/stablecode-completion-alpha-3b-4k

this doesnt have to be super in detail as its pretty easy to understand. Thanks! ❤️

**Comment by abdibrokhim** [comment]
> @abdibrokhim very nice, love this one! 🚀
> 
> one small thing: could you add a paragraph on how to use these models with the hugging face inference api? (not everyone has a good GPU)
> 
> * https://huggingface.co/docs/api-inference/index
> * https://huggingface.co/stabilityai/stablecode-instruct-alpha-3b & https://huggingface.co/stabilityai/stablecode-completion-alpha-3b-4k
> 
> this doesnt have to be super in detail as its pretty easy to understand. Thanks! ❤️

Hello, actually for that reason (not everyone has a good GPU), I went with Google Colab in this tutorial.

**Comment by abdibrokhim** [comment]
> @abdibrokhim very nice, love this one! 🚀
> 
> one small thing: could you add a paragraph on how to use these models with the hugging face inference api? (not everyone has a good GPU)
> 
> * https://huggingface.co/docs/api-inference/index
> * https://huggingface.co/stabilityai/stablecode-instruct-alpha-3b & https://huggingface.co/stabilityai/stablecode-completion-alpha-3b-4k
> 
> this doesnt have to be super in detail as its pretty easy to understand. Thanks! ❤️

**Comment by abdibrokhim** [comment]
anyway lemme add this feature

**Comment by ezzcodeezzlife** [comment]
Epic, thank you!

**Comment by ezzcodeezzlife** [comment]
Is that all from your side?

**Comment by ezzcodeezzlife** [comment]
@VolodymyrStreltsov can you also please check SEO here? thanks!

**Review by VolodymyrStreltsov — APPROVED** [review]

**Comment by abdibrokhim** [comment]
hello @ezzcodeezzlife when will you merge?

**Comment by ezzcodeezzlife** [comment]
@abdibrokhim can you please have a look at the conflicts? thanks

**Comment by abdibrokhim** [comment]
> @abdibrokhim can you please have a look at the conflicts? thanks

what conflicts? @VolodymyrStreltsov  already approved tutorial

**Comment by ezzcodeezzlife** [comment]
image

**Comment by abdibrokhim** [comment]
@ezzcodeezzlife  tutorial was approved but not rewarded yet

**Pull request closed without merging**
