### PR TITLE
monday.com Tutorial: Create and publish your first monday.com AI App with Stable Diffusion

### PR DESCRIPTION
**Pull request by abdibrokhim**
/claim #161 

monday.com Tutorial: Create and publish your first monday.com AI App with Stable Diffusion

In this tutorial, we will learn how to build monday.com AI-powered app using image generative AI (like Stable Diffusion) and publish it. Sit back relax and enjoy the tutorial!

### CODE REVIEW

**Comment by abdibrokhim** [comment]
> please clean up the PR and upload images like explained in the given documentation. Thank you!

thank you man, but there are a lot of images , if you scroll down you can see i explained step by step

**Comment by ezzcodeezzlife** [comment]
Upload images to [this service](https://freeimage.host/) and provide a like that looks like: https://iili.io/HPaF59p.png and then delete them from the PR

thank youu!

**Comment by abdibrokhim** [comment]
@ezzcodeezzlife i have one question how to clear PR? and just leave last commit

**Comment by ezzcodeezzlife** [comment]
throw out files like `.DS_Store` remove the useless chirp tutorial directory etc. & place the tutorial in the right directory, not a sub folder

**Pull request closed without merging**
