### PR TITLE
cohere claim action

### PR DESCRIPTION
**Pull request by shreya50**
/claim #226

### CODE REVIEW

**Comment by shreya50** [comment]
I commented everywhere now

**Comment by ezzcodeezzlife** [comment]
@shreya50 please clean up the file in your PR: `tutorials/claim.mdx`. Thanks! 🚀

**Comment by shreya50** [comment]
> @shreya50 please clean up the file in your PR: `tutorials/claim.mdx`. Thanks! 🚀

idk, I deleted the claim.mdx file in the PR. I don't know what to do anymore

**Comment by shreya50** [comment]
> > @shreya50 please clean up the file in your PR: `tutorials/claim.mdx`. Thanks! 🚀
> 
> idk, I deleted the claim.mdx file in the PR. I don't know what to do anymore

My article has already been published on hackernoon without any revisions a month ago. I'm not supposed to make any changes to it

**Pull request closed without merging**
