### PR TITLE
LLaVA + Fuyu-8B: Overview And The Usage Of The Models #386

### PR DESCRIPTION
**Pull request by adamrayed**
claim #386

### CODE REVIEW

**Comment by OlesiaZinchenko** [comment]
@mkbctrl @ezzcodeezzlife Please, take some time to review the tutorial.

**Comment by adamrayed** [comment]
@OlesiaZinchenko  Any update

**Comment by adamrayed** [comment]
okay 1 min

**Comment by ezzcodeezzlife** [comment]
@adamrayed thank you! 🚀

**Pull request merged**
