### PR TITLE
chatgpt plugin tutorial

### PR DESCRIPTION
**Pull request by alhuissi**
/claim #164 

ChatGPT tutorial: How to build a ChatGPT plugin using ChatGPT

### CODE REVIEW

**Comment by OlesiaZinchenko** [comment]
@ezzcodeezzlife Please, let me know once it will be published

**Comment by ezzcodeezzlife** [comment]
https://github.com/lablab-ai/community-content/tree/main/tutorials make sure you upload the images in the way its descibed in the guidelines. @alhuissi 

thank you for understanding ❤️

**Comment by alhuissi** [comment]
@ezzcodeezzlife done!

**Comment by ezzcodeezzlife** [comment]
thank you! @alhuissi

**Pull request merged**
